name: Deploy

on:
  push:
    tags:
      - v*.*.*
    branches:
      - master # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Dependencies Install
      run: npm install

    - name: Build library
      run: npm run build ngx-keypad -- --prod

    - name: Build sample
      run: npm run build --prod

    - name: Copy file via scp
      uses: appleboy/scp-action@master              
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "./dist/ngx-keypad-demo"
        target: ${{ secrets.COPY_TO }}

    - name: Move files to correct place
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: mv ${{ secrets.COPY_FROM }} ${{ secrets.COPY_TO }};rm -rf ${{ secrets.TO_REMOVE }};chcon -Rt httpd_sys_content_t ${{ secrets.COPY_TO }}; nginx -s reload
